name: Compile Marian model

on:
  workflow_dispatch:
    inputs:
      quantization:
        description: "Choose quantization for model"
        required: true
        default: "q0f32"
        type: choice
        options:
          - q0f32
          - q4f16

jobs:
  run-in-container:
    runs-on: ubuntu-latest
    container:
      image: olyasir/models_build:ubuntu22.04_vulkan

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Only fetch the latest commit

      # - name: check space 1
      #   shell: bash
      #   run: du -h / | sort -h | tail -n 10 && \ 
      #        df -h

      # - name: check space 2
      #   shell: bash
      #   run: df -h

      - name: Install Rust manually
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH  # Add Rust to the PATH for GitHub Actions

      - name: Source Rust environment
        shell: bash
        run: source $HOME/.cargo/env && rustup --version && cargo --version

      - name: Mark repository as safe
        run: |
          git config --global --add safe.directory /__w/mlc-llm/mlc-llm

      - name: get submodules
        run: |
            git submodule update --init --recursive


      - name: Run a command in the container
        run: |
          echo "Verifying vulkan instalation "
          python --version
          vulkaninfo
          cargo --version
          pwd 
          rustup --version

    
      - name: Download model
        run: git-lfs install && git clone https://huggingface.co/Helsinki-NLP/opus-mt-en-it

      - name: Create build directory
        shell: bash
        run: mkdir build && cd build && cp ../cmake/config.cmake . && cmake ..

      - name: Build the project
        shell: bash
        run: |
           source $HOME/.cargo/env && cd build && cmake --build . 
    
   

      - name: cleanup 
        run: rm -rf $HOME/.cargo $HOME/.rustup 3rdpary/tvm /tvm

      - name: check space
        shell: bash
        run: du -h / | sort -h | tail -n 10

      - name: Install mlc-llm
        run: |
           cd python && pip install -e .

      - name: Compile model
        run: |
            ./ci/models_build/marian.sh

      - name: Upload compied model as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-q0f32-opus-mt-en-it
          path: output-q0f32-opus-mt-en-it/
            
