name: Build for macOS with Metal Backend

on:
  workflow_dispatch:
    inputs:
      quantization:
        description: "Choose quantization for model"
        required: true
        default: "q0f32"
        type: choice
        options:
          - q0f32
          - q4f32_1
      language_pair:
        description: "language pair"
        required: true
        default: "en-it"
        type: string

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install llvm cmake git python@3.11  git-lfs
          python3.11 -m venv ./venv
          source ./venv/bin/activate
          python3.11 -m pip install --upgrade pip

      - name: Download model
        run: |
          git-lfs install
          git clone --depth 1 https://huggingface.co/Helsinki-NLP/opus-mt-${{ github.event.inputs.language_pair }}


      - name: Clone and Build TVM with Metal
        run: |
          source ./venv/bin/activate
          cd ..
          git clone --recursive https://github.com/apache/tvm tvm
          cd tvm
          git reset --hard d5b9f5c30bc3e1f5e1a283ed19c5440afcc45889
          mkdir build
          cd build
          cp ../cmake/config.cmake .
          echo "set(CMAKE_BUILD_TYPE RelWithDebInfo)" >> config.cmake
          echo "set(USE_LLVM \"llvm-config --ignore-libllvm --link-static\")" >> config.cmake
          echo "set(HIDE_PRIVATE_SYMBOLS ON)" >> config.cmake
          echo "set(USE_METAL ON)" >> config.cmake
          cmake ..
          # sed -i '' 's/\/opt\/homebrew/\/Users\/dev\/.local/g' ./CMakeFiles/tvm.dir/link.txt
          # sed -i '' 's/\/opt\/homebrew/\/Users\/dev\/.local/g' ./CMakeFiles/tvm.dir/build.make
          cmake --build . --parallel 30
          cd ..
          cd python
          pip install -e .

     
      - name: Create build directory
        shell: bash
        run: |
          source ./venv/bin/activate
          mkdir build
          cd build
          cp ../cmake/config.cmake .
          echo "set(TVM_SOURCE_DIR, $GITHUB_WORKSPACE/../tvm)" >> config.cmake
          echo "set(USE_METAL ON)" >> config.cmake
          cmake .. 

      - name: Build the project
        shell: bash
        run: |
          # source $HOME/.cargo/env
          source ./venv/bin/activate
          cd build
          cmake --build . --parallel 30

      # - name: Cleanup to free space
      #   run: |
      #     echo "Cleaning up to free disk space"
      #     rm -rf $HOME/.cargo $HOME/.rustup 3rdparty/tvm /__t/CodeQL

      - name: Install mlc-llm
        run: |
          source ./venv/bin/activate
          cd python
          pip install -e .

      - name: Compile model
        run: |
          ./ci/models_build/marian.sh "${{ github.event.inputs.quantization }}" "${{ github.event.inputs.language_pair }}"

      - name: Upload compiled model as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-${{ github.event.inputs.quantization }}-opus-mt-${{ github.event.inputs.language_pair }}
          path: output-${{ github.event.inputs.quantization }}-opus-mt-${{ github.event.inputs.language_pair }}/
